#!/usr/bin/env python3
"""Generate player/font8x16.h: an 8x16 bitmap for ASCII 0x20..0x7E.

One-time dev-host step (needs Pillow + a DejaVu mono TTF). Output is committed;
the board/runtime never runs this. Each glyph is 16 bytes (one per row); bit
0x80 is the leftmost column.

    pip install pillow      # or: apt-get install python3-pil fonts-dejavu-core
    python3 player/tools/gen_font8x16.py
"""
import os
from PIL import Image, ImageFont, ImageDraw

W, H = 8, 16
CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/TTF/DejaVuSansMono.ttf",
    "/Library/Fonts/DejaVuSansMono.ttf",
    "/nix/store/238xkvzxd8wpwxiiffslzi5kfdsql6wj-dejavu-fonts-2.37/share/fonts/truetype/DejaVuSansMono.ttf",
]
path = next((p for p in CANDIDATES if os.path.exists(p)), None)
if not path:
    raise SystemExit("DejaVuSansMono.ttf not found; install fonts-dejavu-core")

font = ImageFont.truetype(path, 14)
rows = []
for code in range(0x20, 0x7F):
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, -1), chr(code), fill=255, font=font)
    px = img.load()
    glyph = []
    for y in range(H):
        bits = 0
        for x in range(W):
            if px[x, y] > 96:
                bits |= 0x80 >> x
        glyph.append(bits)
    rows.append((code, glyph))

with open(os.path.join(os.path.dirname(__file__), "..", "font8x16.h"), "w") as f:
    f.write("#ifndef CITRUSPILOT_FONT8X16_H\n#define CITRUSPILOT_FONT8X16_H\n")
    f.write("#include <stdint.h>\n")
    f.write("/* Generated by tools/gen_font8x16.py. ASCII 0x20..0x7E, 8x16, MSB=left. */\n")
    f.write("static const uint8_t font8x16[95][16] = {\n")
    for code, glyph in rows:
        body = ",".join("0x%02x" % b for b in glyph)
        f.write("    { %s }, /* 0x%02x '%s' */\n"
                % (body, code, chr(code) if code != 0x20 else " "))
    f.write("};\n#endif\n")
print("wrote player/font8x16.h")
